### ISSUE TITLE
some issues for tonis

### ISSUE THREAD

**Issue by juliomatcom** [tonis-io/web#3]
Hi there, im going to tell some issues in a small review i can suggest to this project:

1- $tonis = (new \Tonis\Tonis\Factory\TonisFactory)->createWeb();

Please nobodys want to write that namespace, just named Tonis\App()
- May i say you are not create a Web you are create an Application, a Server instance maybe.

2- Personally $routes = $tonis->routes();
  if you want access to a property member like the routes the correct name is getRoutes()
but if you return an Class to do something like $routes->get(...) maybe the correct name is not $routes , i suggest other like $router becouse it have actions, add/process routes in your App , or just $routes->add(METHOD,ACTION)

3- Annotation, pls document  your methods, people want to know what a method do, without to look the source code.
4- Add some index.php with basic example of use, for newbies

**Comment by spiffyjr** [comment]
1. I'll shorten the namespace but I'd argue most people will be copy pasting or using the sample project (tonis-io/tonis-project).
2. Routes returns a RouteCollection so it's appropriate naming. I could have yet another classed name Router with a route() method if I really wanted to separate that concern but it's overdoing it in my opnion.
3. Yes, I agree. I'll add more docblocks as time goes on.
4. I plan on doing just that with the tonis-project mentioned above.

Thanks for your input.

**Comment by juliomatcom** [comment]
Good, just:
2- Is confussing use $routes->get() to add an Action on a GET Request, normally doing get() on a Collection will return an element dont you think ?

**Comment by spiffyjr** [comment]
Good point. I'll split out the Router, add a getRouter() to Tonis and move the HTTP verbs to the router.

**Comment by spiffyjr** [comment]
This was fixed by tonis-io/router#48a10644359b084c8965853d39d5abf0c9182f52
